var RO_DATABASE_ITEMS = {
  ITEMS: {
    // --- 武器區 (Weapons) - 各系武器保留經典並補足 ---
    weapons: [
      // 短劍 (Daggers)
      { id: 'w_001', name: '笨拙短劍', type: 'weapon', reqLevel: 1, reqClass: ['all'], attr: { atk: 17 } },
      { id: 'w_002', name: '短劍', type: 'weapon', reqLevel: 12, reqClass: ['swordman', 'thief', 'magician', 'merchant', 'novice'], attr: { atk: 43 } },
      { id: 'w_003', name: '大馬士革短劍', type: 'weapon', reqLevel: 24, reqClass: ['swordman', 'thief', 'magician', 'merchant'], attr: { atk: 118 } },
      { id: 'w_004', name: '刺客匕首', type: 'weapon', reqLevel: 40, reqClass: ['thief'], attr: { atk: 140, flee: 10, crit: 5 } },
      { id: 'w_005', name: '神聖之首', type: 'weapon', reqLevel: 60, reqClass: ['swordman', 'thief'], attr: { atk: 165, hit: 20 } },
      { id: 'w_006', name: '幸運短劍', type: 'weapon', reqLevel: 70, reqClass: ['all'], attr: { atk: 120, luk: 15, crit: 10 } },
      { id: 'w_007', name: '月光匕首', type: 'weapon', reqLevel: 80, reqClass: ['magician', 'thief'], attr: { atk: 150, maxSp: 200, int: 5 } },
      { id: 'w_008', name: '破甲短劍', type: 'weapon', reqLevel: 95, reqClass: ['thief', 'merchant'], attr: { atk: 190, dex: 5 } },
      { id: 'w_009', name: '神聖天使之刃', type: 'weapon', reqLevel: 120, reqClass: ['thief', 'swordman'], attr: { atk: 240, hit: 30, str: 5 } },
      { id: 'w_010', name: '除靈短劍', type: 'weapon', reqLevel: 65, reqClass: ['thief', 'acolyte'], attr: { atk: 130, int: 3, matk: 50 } },

      // 單手劍/雙手劍 (Swords)
      { id: 'w_101', name: '長劍', type: 'weapon', reqLevel: 10, reqClass: ['swordman', 'merchant', 'thief'], attr: { atk: 45 } },
      { id: 'w_102', name: '圓月彎刀', type: 'weapon', reqLevel: 20, reqClass: ['swordman', 'thief'], attr: { atk: 85 } },
      { id: 'w_103', name: '海東劍', type: 'weapon', reqLevel: 35, reqClass: ['swordman', 'merchant'], attr: { atk: 120 } },
      { id: 'w_104', name: '狂擊之劍', type: 'weapon', reqLevel: 50, reqClass: ['swordman'], attr: { atk: 150, str: 3, hit: 5 } },
      { id: 'w_105', name: '雙手巨劍', type: 'weapon', reqLevel: 33, reqClass: ['swordman'], attr: { atk: 160 } },
      { id: 'w_106', name: '焰形劍', type: 'weapon', reqLevel: 60, reqClass: ['swordman'], attr: { atk: 200, str: 2 } },
      { id: 'w_107', name: '名刀 不知火', type: 'weapon', reqLevel: 75, reqClass: ['swordman'], attr: { atk: 250, crit: 20, agi: 3 } },
      { id: 'w_108', name: '水紋劍', type: 'weapon', reqLevel: 85, reqClass: ['swordman'], attr: { atk: 280, hit: 30, maxHp: 500 } },
      { id: 'w_109', name: '狂君之劍', type: 'weapon', reqLevel: 110, reqClass: ['swordman'], attr: { atk: 350, str: 8, maxHp: 1000 } },
      { id: 'w_110', name: '妖刀 村正', type: 'weapon', reqLevel: 90, reqClass: ['swordman'], attr: { atk: 260, crit: 30, agi: 5 } },
      { id: 'w_111', name: '聖劍 勝利之劍', type: 'weapon', reqLevel: 100, reqClass: ['swordman'], attr: { atk: 300, str: 5, int: 5, hit: 20 } },

      // 斧頭 (Axes)
      { id: 'w_201', name: '手斧', type: 'weapon', reqLevel: 10, reqClass: ['swordman', 'merchant'], attr: { atk: 50 } },
      { id: 'w_202', name: '戰鬥斧', type: 'weapon', reqLevel: 30, reqClass: ['swordman', 'merchant'], attr: { atk: 130 } },
      { id: 'w_203', name: '雙手斧', type: 'weapon', reqLevel: 50, reqClass: ['merchant', 'swordman'], attr: { atk: 185 } },
      { id: 'w_204', name: '血斧', type: 'weapon', reqLevel: 70, reqClass: ['merchant'], attr: { atk: 250, str: 5, agi: 2 } },
      { id: 'w_205', name: '毀滅之斧', type: 'weapon', reqLevel: 85, reqClass: ['merchant'], attr: { atk: 320, vit: 3 } },
      { id: 'w_206', name: '颶風之斧', type: 'weapon', reqLevel: 105, reqClass: ['merchant'], attr: { atk: 400, str: 10 } },
      { id: 'w_207', name: '斬首之斧', type: 'weapon', reqLevel: 95, reqClass: ['merchant', 'swordman'], attr: { atk: 350, hit: -10, str: 8 } },

      // 鈍器 (Maces)
      { id: 'w_301', name: '棍棒', type: 'weapon', reqLevel: 5, reqClass: ['swordman', 'merchant', 'acolyte'], attr: { atk: 23 } },
      { id: 'w_302', name: '流星鎚', type: 'weapon', reqLevel: 15, reqClass: ['swordman', 'merchant', 'acolyte'], attr: { atk: 65 } },
      { id: 'w_303', name: '鐵鎚', type: 'weapon', reqLevel: 25, reqClass: ['swordman', 'merchant', 'acolyte'], attr: { atk: 90 } },
      { id: 'w_304', name: '十字架', type: 'weapon', reqLevel: 40, reqClass: ['acolyte'], attr: { atk: 110, matk: 80, int: 2 } },
      { id: 'w_305', name: '審判十字架', type: 'weapon', reqLevel: 65, reqClass: ['acolyte'], attr: { atk: 140, matk: 120, int: 4 } },
      { id: 'w_306', name: '黃金之鎚', type: 'weapon', reqLevel: 80, reqClass: ['merchant', 'acolyte'], attr: { atk: 180, hit: 20, maxHp: 300 } },
      { id: 'w_307', name: '復仇者之鎚', type: 'weapon', reqLevel: 100, reqClass: ['acolyte', 'merchant'], attr: { atk: 260, matk: 200, str: 5, int: 5 } },
      { id: 'w_308', name: '尖銳的鐵鎚', type: 'weapon', reqLevel: 50, reqClass: ['swordman', 'merchant'], attr: { atk: 130, crit: 20 } },

      // 法杖 (Staffs)
      { id: 'w_401', name: '木杖', type: 'weapon', reqLevel: 1, reqClass: ['magician', 'acolyte'], attr: { atk: 15, matk: 30 } },
      { id: 'w_402', name: '言靈魔杖', type: 'weapon', reqLevel: 24, reqClass: ['magician', 'acolyte'], attr: { atk: 30, int: 3, matk: 90 } },
      { id: 'w_403', name: '生存的魔杖', type: 'weapon', reqLevel: 40, reqClass: ['magician'], attr: { atk: 50, maxHp: 400, matk: 150, vit: 3 } },
      { id: 'w_404', name: '骷髏魔杖', type: 'weapon', reqLevel: 55, reqClass: ['magician'], attr: { atk: 60, matk: 180, int: 4 } },
      { id: 'w_405', name: '巫術之杖', type: 'weapon', reqLevel: 70, reqClass: ['magician'], attr: { atk: 60, matk: 230, dex: 4, int: 2 } },
      { id: 'w_406', name: '聖職之杖', type: 'weapon', reqLevel: 70, reqClass: ['acolyte'], attr: { atk: 80, matk: 200, int: 5, maxSp: 150 } },
      { id: 'w_407', name: '毀滅魔杖', type: 'weapon', reqLevel: 90, reqClass: ['magician'], attr: { atk: 100, matk: 320, int: 8 } },
      { id: 'w_408', name: '克羅諾斯魔杖', type: 'weapon', reqLevel: 115, reqClass: ['magician'], attr: { atk: 120, matk: 450, int: 12, maxSp: 500 } },
      { id: 'w_409', name: '紅十字刺刃', type: 'weapon', reqLevel: 85, reqClass: ['acolyte'], attr: { atk: 110, matk: 250, maxSp: 200 } },

      // 弓箭 (Bows)
      { id: 'w_501', name: '弓', type: 'weapon', reqLevel: 1, reqClass: ['archer', 'thief'], attr: { atk: 15 } },
      { id: 'w_502', name: '十字弓', type: 'weapon', reqLevel: 18, reqClass: ['archer', 'thief'], attr: { atk: 65, dex: 2 } },
      { id: 'w_503', name: '角弓', type: 'weapon', reqLevel: 33, reqClass: ['archer'], attr: { atk: 100 } },
      { id: 'w_504', name: '獵弓', type: 'weapon', reqLevel: 50, reqClass: ['archer'], attr: { atk: 125, hit: 10, dex: 2 } },
      { id: 'w_505', name: '坎弓', type: 'weapon', reqLevel: 65, reqClass: ['archer'], attr: { atk: 150, dex: 3, agi: 2 } },
      { id: 'w_506', name: '神射手之弓', type: 'weapon', reqLevel: 80, reqClass: ['archer'], attr: { atk: 180, crit: 10, dex: 5, agi: 3 } },
      { id: 'w_507', name: '精靈之弓', type: 'weapon', reqLevel: 100, reqClass: ['archer'], attr: { atk: 250, dex: 8, hit: 30 } },
      { id: 'w_508', name: '巨弓', type: 'weapon', reqLevel: 120, reqClass: ['archer'], attr: { atk: 350, dex: 12 } },
      { id: 'w_509', name: '獸人弓', type: 'weapon', reqLevel: 75, reqClass: ['archer'], attr: { atk: 160, str: 2 } },

      // 拳刃 (Katars)
      { id: 'w_601', name: '拳刃', type: 'weapon', reqLevel: 40, reqClass: ['thief'], attr: { atk: 105, crit: 5 } },
      { id: 'w_602', name: '卡塔勒拳刃', type: 'weapon', reqLevel: 55, reqClass: ['thief'], attr: { atk: 148, crit: 8 } },
      { id: 'w_603', name: '刺客拳刃', type: 'weapon', reqLevel: 70, reqClass: ['thief'], attr: { atk: 180, crit: 15, agi: 2 } },
      { id: 'w_604', name: '爆炎拳刃', type: 'weapon', reqLevel: 85, reqClass: ['thief'], attr: { atk: 210, crit: 10, str: 3 } },
      { id: 'w_605', name: '斬首拳刃', type: 'weapon', reqLevel: 105, reqClass: ['thief'], attr: { atk: 280, crit: 25, str: 5 } },
      { id: 'w_606', name: '指甲', type: 'weapon', reqLevel: 60, reqClass: ['thief'], attr: { atk: 120, agi: 5, flee: 10 } },
    ],
    
    // --- 防具區 ---
    armors: [
      // ---------------- 頭飾 (Helm) - 30件 ----------------
      { id: 'h_001', name: '髮圈', type: 'helm', reqLevel: 1, reqClass: ['all'], attr: { def: 1 } },
      { id: 'h_002', name: '頭巾', type: 'helm', reqLevel: 10, reqClass: ['all'], attr: { def: 2, maxHp: 50 } },
      { id: 'h_003', name: '蘋果頭飾', type: 'helm', reqLevel: 25, reqClass: ['archer', 'thief'], attr: { def: 2, dex: 3 } },
      { id: 'h_004', name: '亡者髮箍', type: 'helm', reqLevel: 30, reqClass: ['swordman', 'merchant'], attr: { def: 4, agi: 2, str: 1 } },
      { id: 'h_005', name: '魔法師帽', type: 'helm', reqLevel: 35, reqClass: ['magician'], attr: { def: 3, int: 2, maxSp: 50 } },
      { id: 'h_006', name: '骨製頭盔', type: 'helm', reqLevel: 50, reqClass: ['swordman'], attr: { def: 7, vit: 2 } },
      { id: 'h_007', name: '王冠', type: 'helm', reqLevel: 70, reqClass: ['all'], attr: { def: 5, int: 3, luk: 3 } },
      { id: 'h_008', name: '惡魔翅膀耳飾', type: 'helm', reqLevel: 85, reqClass: ['all'], attr: { def: 2, str: 2, int: 2 } },
      { id: 'h_009', name: '太陽神頭盔', type: 'helm', reqLevel: 100, reqClass: ['swordman', 'merchant'], attr: { def: 10, str: 3, vit: 3, maxHp: 500 } },
      { id: 'h_010', name: '糞便帽', type: 'helm', reqLevel: 30, reqClass: ['all'], attr: { def: 2, maxHp: 100 } },
      { id: 'h_011', name: '貓耳髮圈', type: 'helm', reqLevel: 20, reqClass: ['all'], attr: { def: 2, agi: 2 } },
      { id: 'h_012', name: '兔耳髮圈', type: 'helm', reqLevel: 20, reqClass: ['all'], attr: { def: 2, luk: 2 } },
      { id: 'h_013', name: '鋼鐵頭盔', type: 'helm', reqLevel: 40, reqClass: ['swordman', 'merchant'], attr: { def: 6 } },
      { id: 'h_014', name: '獸人頭盔', type: 'helm', reqLevel: 55, reqClass: ['swordman'], attr: { def: 8, str: 2 } },
      { id: 'h_015', name: '領導者頭箍', type: 'helm', reqLevel: 60, reqClass: ['swordman'], attr: { def: 6, str: 1, vit: 1 } },
      { id: 'h_016', name: '聖職之帽', type: 'helm', reqLevel: 40, reqClass: ['acolyte'], attr: { def: 4, int: 2 } },
      { id: 'h_017', name: '小丑帽', type: 'helm', reqLevel: 50, reqClass: ['all'], attr: { def: 3, luk: 5 } },
      { id: 'h_018', name: '歌舞伎面具', type: 'helm', reqLevel: 65, reqClass: ['all'], attr: { def: 4, hit: 5 } },
      { id: 'h_019', name: '狐狸面具', type: 'helm', reqLevel: 65, reqClass: ['all'], attr: { def: 4, agi: 3 } },
      { id: 'h_020', name: '舞會面具', type: 'helm', reqLevel: 65, reqClass: ['all'], attr: { def: 3, flee: 5 } },
      { id: 'h_021', name: '劍聖王冠', type: 'helm', reqLevel: 80, reqClass: ['swordman'], attr: { def: 8, str: 3, dex: 2 } },
      { id: 'h_022', name: '蜂后冠', type: 'helm', reqLevel: 80, reqClass: ['magician'], attr: { def: 5, int: 3, maxSp: 100 } },
      { id: 'h_023', name: '懶洋洋的貓', type: 'helm', reqLevel: 45, reqClass: ['all'], attr: { def: 3, flee: 10 } },
      { id: 'h_024', name: '天使紙袋', type: 'helm', reqLevel: 25, reqClass: ['all'], attr: { def: 1, maxHp: 50, maxSp: 50 } },
      { id: 'h_025', name: '惡魔侍者角', type: 'helm', reqLevel: 75, reqClass: ['all'], attr: { def: 5, str: 3, maxSp: 50 } },
      { id: 'h_026', name: '惡魔女僕角', type: 'helm', reqLevel: 75, reqClass: ['all'], attr: { def: 5, int: 3, maxHp: 50 } },
      { id: 'h_027', name: '飛行帽', type: 'helm', reqLevel: 60, reqClass: ['archer'], attr: { def: 4, dex: 2, agi: 2 } },
      { id: 'h_028', name: '紅蝶緞帶', type: 'helm', reqLevel: 15, reqClass: ['all'], attr: { def: 2, int: 1 } },
      { id: 'h_029', name: '藍波利帽', type: 'helm', reqLevel: 15, reqClass: ['all'], attr: { def: 2, luk: 3 } },
      { id: 'h_030', name: '海盜船長帽', type: 'helm', reqLevel: 85, reqClass: ['merchant', 'swordman'], attr: { def: 7, str: 2, vit: 2 } },

      // ---------------- 鎧甲 (Body) - 30件 ----------------
      { id: 'a_001', name: '棉襯衫', type: 'armor', reqLevel: 1, reqClass: ['all'], attr: { def: 1, maxHp: 20 } },
      { id: 'a_002', name: '皮甲', type: 'armor', reqLevel: 5, reqClass: ['all'], attr: { def: 2, maxHp: 50 } },
      { id: 'a_003', name: '絲質外衣', type: 'armor', reqLevel: 10, reqClass: ['magician', 'acolyte'], attr: { def: 3, maxSp: 30, int: 1 } },
      { id: 'a_004', name: '木製鎧甲', type: 'armor', reqLevel: 15, reqClass: ['swordman', 'merchant'], attr: { def: 7, maxHp: 150 } },
      { id: 'a_005', name: '盜賊之衣', type: 'armor', reqLevel: 20, reqClass: ['thief'], attr: { def: 6, agi: 2, flee: 5 } },
      { id: 'a_006', name: '緊身便衣', type: 'armor', reqLevel: 20, reqClass: ['archer'], attr: { def: 5, dex: 2 } },
      { id: 'a_007', name: '鋼鐵鎧甲', type: 'armor', reqLevel: 40, reqClass: ['swordman', 'merchant'], attr: { def: 12, maxHp: 400 } },
      { id: 'a_008', name: '聖職之衣', type: 'armor', reqLevel: 40, reqClass: ['acolyte'], attr: { def: 6, int: 2, maxSp: 80 } },
      { id: 'a_009', name: '魔法外套', type: 'armor', reqLevel: 50, reqClass: ['magician'], attr: { def: 5, int: 3, maxSp: 150 } },
      { id: 'a_010', name: '神射手之衣', type: 'armor', reqLevel: 65, reqClass: ['archer'], attr: { def: 8, dex: 4, flee: 10 } },
      { id: 'a_011', name: '騎士鎧甲', type: 'armor', reqLevel: 70, reqClass: ['swordman'], attr: { def: 16, maxHp: 1000, vit: 3 } },
      { id: 'a_012', name: '暗殺者外衣', type: 'armor', reqLevel: 75, reqClass: ['thief'], attr: { def: 10, agi: 4, flee: 25 } },
      { id: 'a_013', name: '隕石鎧甲', type: 'armor', reqLevel: 85, reqClass: ['swordman', 'merchant'], attr: { def: 20, maxHp: 1500, vit: 5 } },
      { id: 'a_014', name: '奧丁的祝福', type: 'armor', reqLevel: 90, reqClass: ['all'], attr: { def: 10, str: 2, agi: 2, vit: 2, int: 2, dex: 2, luk: 2 } },
      { id: 'a_015', name: '大天使之衣', type: 'armor', reqLevel: 110, reqClass: ['acolyte', 'magician'], attr: { def: 12, maxHp: 800, maxSp: 400, int: 5 } },
      { id: 'a_016', name: '冒險衣', type: 'armor', reqLevel: 2, reqClass: ['all'], attr: { def: 2 } },
      { id: 'a_017', name: '木鏈甲', type: 'armor', reqLevel: 25, reqClass: ['swordman', 'merchant'], attr: { def: 9, vit: 1 } },
      { id: 'a_018', name: '鋁合金鎧甲', type: 'armor', reqLevel: 60, reqClass: ['swordman'], attr: { def: 14, vit: 2, maxHp: 600 } },
      { id: 'a_019', name: '鱗片鎧甲', type: 'armor', reqLevel: 55, reqClass: ['swordman', 'merchant'], attr: { def: 11, maxHp: 500 } },
      { id: 'a_020', name: '鎖子甲', type: 'armor', reqLevel: 45, reqClass: ['swordman', 'merchant'], attr: { def: 10 } },
      { id: 'a_021', name: '秘銀重甲', type: 'armor', reqLevel: 80, reqClass: ['swordman'], attr: { def: 18, vit: 4, maxSp: 100 } },
      { id: 'a_022', name: '水屬性鎧甲', type: 'armor', reqLevel: 50, reqClass: ['all'], attr: { def: 6, maxHp: 200 } },
      { id: 'a_023', name: '火屬性鎧甲', type: 'armor', reqLevel: 50, reqClass: ['all'], attr: { def: 6, maxHp: 200 } },
      { id: 'a_024', name: '風屬性鎧甲', type: 'armor', reqLevel: 50, reqClass: ['all'], attr: { def: 6, maxHp: 200 } },
      { id: 'a_025', name: '地屬性鎧甲', type: 'armor', reqLevel: 50, reqClass: ['all'], attr: { def: 6, maxHp: 200 } },
      { id: 'a_026', name: '鮮血外衣', type: 'armor', reqLevel: 70, reqClass: ['thief'], attr: { def: 8, agi: 2, str: 2, atk: 10 } },
      { id: 'a_027', name: '忍服 血櫻', type: 'armor', reqLevel: 65, reqClass: ['thief'], attr: { def: 7, agi: 3, flee: 15 } },
      { id: 'a_028', name: '魔王外衣', type: 'armor', reqLevel: 95, reqClass: ['magician', 'acolyte'], attr: { def: 9, int: 4, dex: 3, matk: 30 } },
      { id: 'a_029', name: '龍之外套', type: 'armor', reqLevel: 85, reqClass: ['archer', 'thief'], attr: { def: 10, dex: 3, agi: 3 } },
      { id: 'a_030', name: '艾克賽利翁外套', type: 'armor', reqLevel: 100, reqClass: ['all'], attr: { def: 15, maxHp: 1000, maxSp: 200, vit: 2 } },

      // ---------------- 披肩 (Garment) - 30件 ----------------
      { id: 'g_001', name: '連帽披肩', type: 'garment', reqLevel: 1, reqClass: ['all'], attr: { def: 1, flee: 2 } },
      { id: 'g_002', name: '披風', type: 'garment', reqLevel: 15, reqClass: ['all'], attr: { def: 2, flee: 5 } },
      { id: 'g_003', name: '斗篷', type: 'garment', reqLevel: 30, reqClass: ['all'], attr: { def: 4, flee: 10 } },
      { id: 'g_004', name: '生存的斗篷', type: 'garment', reqLevel: 50, reqClass: ['magician', 'acolyte'], attr: { def: 3, maxHp: 200 } },
      { id: 'g_005', name: '金屬波利披風', type: 'garment', reqLevel: 55, reqClass: ['all'], attr: { def: 5, maxHp: 300, vit: 1 } },
      { id: 'g_006', name: '暗影披風', type: 'garment', reqLevel: 65, reqClass: ['thief'], attr: { def: 4, flee: 25, agi: 3 } },
      { id: 'g_007', name: '伯爵斗篷', type: 'garment', reqLevel: 80, reqClass: ['all'], attr: { def: 6, hit: 10, flee: 15 } },
      { id: 'g_008', name: '巴風特之角(披風)', type: 'garment', reqLevel: 95, reqClass: ['all'], attr: { def: 5, crit: 5, str: 2 } },
      { id: 'g_009', name: '墮落天使之翼', type: 'garment', reqLevel: 110, reqClass: ['all'], attr: { def: 8, allStat: 3, flee: 30 } },
      { id: 'g_010', name: '破爛披風', type: 'garment', reqLevel: 10, reqClass: ['all'], attr: { def: 1, maxHp: 10 } },
      { id: 'g_011', name: '羊毛圍巾', type: 'garment', reqLevel: 55, reqClass: ['all'], attr: { def: 3, maxHp: 150 } },
      { id: 'g_012', name: '龍的呼吸', type: 'garment', reqLevel: 75, reqClass: ['all'], attr: { def: 6, maxHp: 250, flee: 10 } },
      { id: 'g_013', name: '鷹之披風', type: 'garment', reqLevel: 60, reqClass: ['archer'], attr: { def: 4, dex: 2, hit: 15 } },
      { id: 'g_014', name: '聖天使披風', type: 'garment', reqLevel: 90, reqClass: ['all'], attr: { def: 7, maxSp: 200, int: 2 } },
      { id: 'g_015', name: '惡魔披風', type: 'garment', reqLevel: 90, reqClass: ['all'], attr: { def: 7, str: 2, atk: 15 } },
      { id: 'g_016', name: '巨大白幽靈披風', type: 'garment', reqLevel: 85, reqClass: ['all'], attr: { def: 5, flee: 20, agi: 2 } },
      { id: 'g_017', name: '冒險家披肩', type: 'garment', reqLevel: 20, reqClass: ['all'], attr: { def: 3 } },
      { id: 'g_018', name: '呢絨披風', type: 'garment', reqLevel: 40, reqClass: ['all'], attr: { def: 4, maxSp: 50 } },
      { id: 'g_019', name: '絲質披肩', type: 'garment', reqLevel: 40, reqClass: ['magician', 'acolyte'], attr: { def: 3, int: 1 } },
      { id: 'g_020', name: '守護者披風', type: 'garment', reqLevel: 70, reqClass: ['swordman'], attr: { def: 7, vit: 2 } },
      { id: 'g_021', name: '英雄披風', type: 'garment', reqLevel: 105, reqClass: ['swordman'], attr: { def: 9, str: 3, maxHp: 500 } },
      { id: 'g_022', name: '魔王披風', type: 'garment', reqLevel: 105, reqClass: ['magician', 'acolyte'], attr: { def: 6, int: 3, maxSp: 300 } },
      { id: 'g_023', name: '艾克賽利翁披風', type: 'garment', reqLevel: 100, reqClass: ['all'], attr: { def: 10, flee: 20 } },
      { id: 'g_024', name: '勇者披肩', type: 'garment', reqLevel: 90, reqClass: ['all'], attr: { def: 8, maxHp: 300 } },
      { id: 'g_025', name: '亡靈披風', type: 'garment', reqLevel: 80, reqClass: ['all'], attr: { def: 5, luk: 4 } },
      { id: 'g_026', name: '神聖披風', type: 'garment', reqLevel: 85, reqClass: ['acolyte'], attr: { def: 6, maxSp: 150, int: 2 } },
      { id: 'g_027', name: '幻影披風', type: 'garment', reqLevel: 95, reqClass: ['thief'], attr: { def: 6, flee: 25 } },
      { id: 'g_028', name: '飛龍披風', type: 'garment', reqLevel: 85, reqClass: ['archer'], attr: { def: 7, dex: 3 } },
      { id: 'g_029', name: '戰鬥披風', type: 'garment', reqLevel: 65, reqClass: ['swordman', 'merchant'], attr: { def: 6, str: 1 } },
      { id: 'g_030', name: '秘銀披風', type: 'garment', reqLevel: 75, reqClass: ['all'], attr: { def: 8 } },

      // ---------------- 鞋靴 (Shoes) - 30件 ----------------
      { id: 's_001', name: '涼鞋', type: 'shoes', reqLevel: 1, reqClass: ['all'], attr: { def: 1, maxHp: 15 } },
      { id: 's_002', name: '皮靴', type: 'shoes', reqLevel: 15, reqClass: ['all'], attr: { def: 2, maxHp: 50 } },
      { id: 's_003', name: '長靴', type: 'shoes', reqLevel: 30, reqClass: ['all'], attr: { def: 4, maxHp: 150 } },
      { id: 's_004', name: '魔法師之靴', type: 'shoes', reqLevel: 45, reqClass: ['magician'], attr: { def: 2, maxSp: 100, int: 2 } },
      { id: 's_005', name: '戰士長靴', type: 'shoes', reqLevel: 50, reqClass: ['swordman', 'merchant'], attr: { def: 6, maxHp: 400, str: 1 } },
      { id: 's_006', name: '敏捷長靴', type: 'shoes', reqLevel: 65, reqClass: ['thief', 'archer'], attr: { def: 5, agi: 4, flee: 20 } },
      { id: 's_007', name: '玻璃鞋', type: 'shoes', reqLevel: 75, reqClass: ['all'], attr: { def: 3, luk: 5, matk: 30 } },
      { id: 's_008', name: '時光力量戰靴', type: 'shoes', reqLevel: 100, reqClass: ['swordman', 'merchant', 'thief'], attr: { def: 8, str: 5, maxHp: 800, atk: 50 } },
      { id: 's_009', name: '時光靈巧戰靴', type: 'shoes', reqLevel: 100, reqClass: ['archer'], attr: { def: 8, dex: 5, maxHp: 500, maxSp: 100, atk: 30 } },
      { id: 's_010', name: '輕便鞋', type: 'shoes', reqLevel: 10, reqClass: ['all'], attr: { def: 2, flee: 2 } },
      { id: 's_011', name: '戰鬥靴', type: 'shoes', reqLevel: 35, reqClass: ['swordman', 'merchant'], attr: { def: 5, maxHp: 200 } },
      { id: 's_012', name: '鋼鐵長靴', type: 'shoes', reqLevel: 60, reqClass: ['swordman'], attr: { def: 8, vit: 2 } },
      { id: 's_013', name: '秘銀長靴', type: 'shoes', reqLevel: 80, reqClass: ['swordman', 'merchant'], attr: { def: 10, vit: 3, maxHp: 400 } },
      { id: 's_014', name: '兔斯基鞋', type: 'shoes', reqLevel: 40, reqClass: ['all'], attr: { def: 3, agi: 2 } },
      { id: 's_015', name: '兔子拖鞋', type: 'shoes', reqLevel: 25, reqClass: ['all'], attr: { def: 2, luk: 3 } },
      { id: 's_016', name: '聖職之靴', type: 'shoes', reqLevel: 55, reqClass: ['acolyte'], attr: { def: 4, int: 2, maxSp: 100 } },
      { id: 's_017', name: '魔王長靴', type: 'shoes', reqLevel: 95, reqClass: ['magician', 'acolyte'], attr: { def: 5, int: 4, maxSp: 250 } },
      { id: 's_018', name: '變異的靴子', type: 'shoes', reqLevel: 85, reqClass: ['all'], attr: { def: 7, maxHp: 1000, maxSp: 300 } },
      { id: 's_019', name: '審判之靴', type: 'shoes', reqLevel: 90, reqClass: ['acolyte'], attr: { def: 6, int: 3, matk: 50 } },
      { id: 's_020', name: '龍之長靴', type: 'shoes', reqLevel: 85, reqClass: ['archer', 'thief'], attr: { def: 6, agi: 3, maxHp: 300 } },
      { id: 's_021', name: '冒險家長靴', type: 'shoes', reqLevel: 20, reqClass: ['all'], attr: { def: 3, maxHp: 100 } },
      { id: 's_022', name: '羊毛長靴', type: 'shoes', reqLevel: 65, reqClass: ['all'], attr: { def: 5, maxHp: 250 } },
      { id: 's_023', name: '艾克賽利翁長靴', type: 'shoes', reqLevel: 100, reqClass: ['all'], attr: { def: 10, maxHp: 500, maxSp: 200 } },
      { id: 's_024', name: '幻影長靴', type: 'shoes', reqLevel: 90, reqClass: ['thief'], attr: { def: 5, flee: 15, agi: 4 } },
      { id: 's_025', name: '英雄長靴', type: 'shoes', reqLevel: 105, reqClass: ['swordman'], attr: { def: 12, vit: 4, maxHp: 800 } },
      { id: 's_026', name: '銀色長靴', type: 'shoes', reqLevel: 45, reqClass: ['all'], attr: { def: 5, maxSp: 50 } },
      { id: 's_027', name: '時光智力戰靴', type: 'shoes', reqLevel: 100, reqClass: ['magician', 'acolyte'], attr: { def: 6, int: 5, maxSp: 300, matk: 50 } },
      { id: 's_028', name: '時光體力戰靴', type: 'shoes', reqLevel: 100, reqClass: ['swordman'], attr: { def: 10, vit: 5, maxHp: 1200 } },
      { id: 's_029', name: '時光敏捷戰靴', type: 'shoes', reqLevel: 100, reqClass: ['thief'], attr: { def: 6, agi: 5, flee: 30, atk: 20 } },
      { id: 's_030', name: '時光幸運戰靴', type: 'shoes', reqLevel: 100, reqClass: ['all'], attr: { def: 6, luk: 5, crit: 15 } },

      // ---------------- 盾牌 (Shields) - 30件 ----------------
      { id: 'sh_001', name: '圓盾', type: 'shield', reqLevel: 10, reqClass: ['all'], attr: { def: 3 } },
      { id: 'sh_002', name: '鐵盾', type: 'shield', reqLevel: 30, reqClass: ['swordman', 'merchant'], attr: { def: 6 } },
      { id: 'sh_003', name: '魔法書', type: 'shield', reqLevel: 35, reqClass: ['magician'], attr: { def: 2, int: 2, matk: 30 } },
      { id: 'sh_004', name: '鋼盾', type: 'shield', reqLevel: 50, reqClass: ['swordman', 'merchant'], attr: { def: 9, vit: 1 } },
      { id: 'sh_005', name: '聖職之盾', type: 'shield', reqLevel: 55, reqClass: ['acolyte'], attr: { def: 5, maxSp: 80, int: 1 } },
      { id: 'sh_006', name: '謊言紀錄本', type: 'shield', reqLevel: 70, reqClass: ['magician'], attr: { def: 4, int: 3, matk: 50 } },
      { id: 'sh_007', name: '十字盾', type: 'shield', reqLevel: 85, reqClass: ['swordman'], attr: { def: 12, vit: 3, maxHp: 500 } },
      { id: 'sh_008', name: '巴基力的鋼盾', type: 'shield', reqLevel: 105, reqClass: ['all'], attr: { def: 15, allStat: 2, maxHp: 800, maxSp: 200 } },
      { id: 'sh_009', name: '護盾', type: 'shield', reqLevel: 5, reqClass: ['all'], attr: { def: 2 } },
      { id: 'sh_010', name: '巨盾', type: 'shield', reqLevel: 45, reqClass: ['swordman'], attr: { def: 10, flee: -10 } },
      { id: 'sh_011', name: '鏡盾', type: 'shield', reqLevel: 65, reqClass: ['swordman', 'merchant'], attr: { def: 8, maxHp: 300 } },
      { id: 'sh_012', name: '聖文盾牌', type: 'shield', reqLevel: 75, reqClass: ['acolyte'], attr: { def: 7, int: 2, maxSp: 150 } },
      { id: 'sh_013', name: '記憶之書', type: 'shield', reqLevel: 80, reqClass: ['magician'], attr: { def: 5, int: 4, matk: 80 } },
      { id: 'sh_014', name: '盤石盾', type: 'shield', reqLevel: 80, reqClass: ['swordman', 'merchant'], attr: { def: 11, vit: 2 } },
      { id: 'sh_015', name: '刺尾龍盾', type: 'shield', reqLevel: 90, reqClass: ['all'], attr: { def: 9, maxHp: 400 } },
      { id: 'sh_016', name: '薔薇鋼盾', type: 'shield', reqLevel: 95, reqClass: ['swordman'], attr: { def: 13, maxHp: 600 } },
      { id: 'sh_017', name: '鈽鐳金盾', type: 'shield', reqLevel: 100, reqClass: ['swordman', 'merchant'], attr: { def: 14, vit: 3 } },
      { id: 'sh_018', name: '魔力石盾', type: 'shield', reqLevel: 90, reqClass: ['magician'], attr: { def: 6, maxSp: 300 } },
      { id: 'sh_019', name: '魔法反射盾', type: 'shield', reqLevel: 95, reqClass: ['swordman'], attr: { def: 10, maxHp: 500 } },
      { id: 'sh_020', name: '冒險家之盾', type: 'shield', reqLevel: 20, reqClass: ['all'], attr: { def: 4 } },
      { id: 'sh_021', name: '獸人族盾牌', type: 'shield', reqLevel: 60, reqClass: ['all'], attr: { def: 7, maxHp: 200 } },
      { id: 'sh_022', name: '皇家盾牌', type: 'shield', reqLevel: 85, reqClass: ['swordman'], attr: { def: 12, maxHp: 400 } },
      { id: 'sh_023', name: '龍之盾', type: 'shield', reqLevel: 75, reqClass: ['swordman', 'merchant'], attr: { def: 9, maxHp: 300 } },
      { id: 'sh_024', name: '魔王之盾', type: 'shield', reqLevel: 105, reqClass: ['magician', 'acolyte'], attr: { def: 8, maxSp: 200, int: 3 } },
      { id: 'sh_025', name: '幻影圓盾', type: 'shield', reqLevel: 90, reqClass: ['thief'], attr: { def: 7, flee: 10 } },
      { id: 'sh_026', name: '艾克賽利翁盾', type: 'shield', reqLevel: 100, reqClass: ['all'], attr: { def: 12, maxHp: 500, maxSp: 100 } },
      { id: 'sh_027', name: '守護者之盾', type: 'shield', reqLevel: 80, reqClass: ['swordman'], attr: { def: 11, vit: 2 } },
      { id: 'sh_028', name: '英雄之盾', type: 'shield', reqLevel: 110, reqClass: ['swordman'], attr: { def: 16, vit: 5, maxHp: 1000 } },
      { id: 'sh_029', name: '黃金之盾', type: 'shield', reqLevel: 85, reqClass: ['all'], attr: { def: 9, luk: 3 } },
      { id: 'sh_030', name: '聖騎士之盾', type: 'shield', reqLevel: 95, reqClass: ['swordman'], attr: { def: 14, vit: 4, int: 2 } },
    ],

    // --- 飾品 (Accessories) - 30件 ---
    accessories: [
      { id: 'ac_001', name: '夾子', type: 'acc', reqLevel: 10, reqClass: ['all'], attr: { maxSp: 30 } },
      { id: 'ac_002', name: '力量戒指', type: 'acc', reqLevel: 20, reqClass: ['swordman', 'merchant', 'thief'], attr: { atk: 15, str: 2 } },
      { id: 'ac_003', name: '智力耳環', type: 'acc', reqLevel: 20, reqClass: ['magician', 'acolyte'], attr: { int: 2, maxSp: 50, matk: 20 } },
      { id: 'ac_004', name: '敏捷胸針', type: 'acc', reqLevel: 20, reqClass: ['archer', 'thief'], attr: { flee: 5, agi: 2 } },
      { id: 'ac_005', name: '幸運珠鍊', type: 'acc', reqLevel: 20, reqClass: ['all'], attr: { crit: 3, luk: 2 } },
      { id: 'ac_006', name: '體力項鍊', type: 'acc', reqLevel: 20, reqClass: ['swordman', 'merchant'], attr: { maxHp: 150, vit: 2 } },
      { id: 'ac_007', name: '靈巧手套', type: 'acc', reqLevel: 20, reqClass: ['archer'], attr: { hit: 10, dex: 2 } },
      { id: 'ac_008', name: '防禦手套', type: 'acc', reqLevel: 50, reqClass: ['all'], attr: { def: 2, maxHp: 150 } },
      { id: 'ac_009', name: '盜賊戒指', type: 'acc', reqLevel: 70, reqClass: ['thief'], attr: { str: 1, agi: 1, crit: 5 } },
      { id: 'ac_010', name: '防禦戒指', type: 'acc', reqLevel: 60, reqClass: ['all'], attr: { def: 3, vit: 1 } },
      { id: 'ac_011', name: '戰神戒指', type: 'acc', reqLevel: 80, reqClass: ['swordman'], attr: { str: 3, maxHp: 300, atk: 20 } },
      { id: 'ac_012', name: '專家戒指', type: 'acc', reqLevel: 80, reqClass: ['all'], attr: { maxSp: 100, matk: 30 } },
      { id: 'ac_013', name: '詛咒紅寶石', type: 'acc', reqLevel: 40, reqClass: ['all'], attr: { luk: -5, atk: 30, matk: 30 } },
      { id: 'ac_014', name: '髮夾', type: 'acc', reqLevel: 1, reqClass: ['all'], attr: { maxSp: 10 } },
      { id: 'ac_015', name: '體力別針', type: 'acc', reqLevel: 45, reqClass: ['swordman', 'merchant'], attr: { maxHp: 200, vit: 3 } },
      { id: 'ac_016', name: '靈巧別針', type: 'acc', reqLevel: 45, reqClass: ['archer'], attr: { hit: 15, dex: 3 } },
      { id: 'ac_017', name: '幸運別針', type: 'acc', reqLevel: 45, reqClass: ['all'], attr: { crit: 5, luk: 3 } },
      { id: 'ac_018', name: '敏捷別針', type: 'acc', reqLevel: 45, reqClass: ['thief', 'archer'], attr: { flee: 8, agi: 3 } },
      { id: 'ac_019', name: '智力別針', type: 'acc', reqLevel: 45, reqClass: ['magician', 'acolyte'], attr: { maxSp: 80, int: 3 } },
      { id: 'ac_020', name: '力量別針', type: 'acc', reqLevel: 45, reqClass: ['swordman', 'merchant'], attr: { atk: 25, str: 3 } },
      { id: 'ac_021', name: '奧爾里昂的手套', type: 'acc', reqLevel: 90, reqClass: ['magician'], attr: { dex: 2, matk: 50 } },
      { id: 'ac_022', name: '奧爾里昂的項鍊', type: 'acc', reqLevel: 90, reqClass: ['magician'], attr: { int: 2, maxSp: 150 } },
      { id: 'ac_023', name: '核心01', type: 'acc', reqLevel: 85, reqClass: ['all'], attr: { def: 1, int: 2, maxSp: 100 } },
      { id: 'ac_024', name: '核心02', type: 'acc', reqLevel: 85, reqClass: ['all'], attr: { def: 1, str: 2, atk: 20 } },
      { id: 'ac_025', name: '核心03', type: 'acc', reqLevel: 85, reqClass: ['all'], attr: { def: 1, agi: 2, flee: 10 } },
      { id: 'ac_026', name: '核心04', type: 'acc', reqLevel: 85, reqClass: ['all'], attr: { def: 1, dex: 2, hit: 10 } },
      { id: 'ac_027', name: '魔力手鐲', type: 'acc', reqLevel: 65, reqClass: ['magician', 'acolyte'], attr: { int: 1, maxSp: 50, matk: 15 } },
      { id: 'ac_028', name: '詛咒胸針', type: 'acc', reqLevel: 75, reqClass: ['thief'], attr: { crit: 10, luk: -2 } },
      { id: 'ac_029', name: '刺客手銬', type: 'acc', reqLevel: 85, reqClass: ['thief'], attr: { agi: 2, str: 2, crit: 5 } },
      { id: 'ac_030', name: '弓箭手面甲', type: 'acc', reqLevel: 70, reqClass: ['archer'], attr: { dex: 3, hit: 20 } },
    ]
  }
};