export const RO_DATABASE_ITEMS = {
  // 欄位定義 (加上 i1_ 前綴)
  keys: ['i1_id', 'i1_name', 'i1_type', 'i1_reqLevel', 'i1_reqClass', 'i1_attr'],

  // 資料陣列對齊
  data: {
    // ================= 武器區 (Weapons) =================
    weapons: [
      // 【短劍 (Daggers)】
      [ 'w_001', '短劍',           'weapon',   1, ['all'],                                                 { atk: 17 } ],
      [ 'w_002', '笨拙短劍',       'weapon',  12, ['swordman', 'thief', 'magician', 'merchant', 'novice'], { atk: 43 } ],
      [ 'w_003', '大馬士革短劍',   'weapon',  24, ['swordman', 'thief', 'magician', 'merchant'],           { atk: 118 } ],
      [ 'w_004', '刺客匕首',       'weapon',  40, ['thief'],                                               { atk: 140, flee: 10, crit: 5 } ],
      [ 'w_005', '神聖之首',       'weapon',  60, ['swordman', 'thief'],                                   { atk: 165, hit: 20 } ],
      [ 'w_006', '幸運短劍',       'weapon',  70, ['all'],                                                 { atk: 120, luk: 15, crit: 10 } ],
      [ 'w_007', '月光匕首',       'weapon',  80, ['magician', 'thief'],                                   { atk: 150, maxSp: 200, int: 5 } ],
      [ 'w_008', '破甲短劍',       'weapon',  95, ['thief', 'merchant'],                                   { atk: 190, dex: 5 } ],
      [ 'w_009', '神聖天使之刃',   'weapon', 120, ['thief', 'swordman'],                                   { atk: 240, hit: 30, str: 5 } ],
      [ 'w_010', '除靈短劍',       'weapon',  65, ['thief', 'acolyte'],                                    { atk: 130, int: 3, matk: 50 } ],

      // 【單手劍/雙手劍 (Swords)】
      [ 'w_101', '長劍',           'weapon',  10, ['swordman', 'merchant', 'thief'],                       { atk: 45 } ],
      [ 'w_102', '圓月彎刀',       'weapon',  20, ['swordman', 'thief'],                                   { atk: 85 } ],
      [ 'w_103', '海東劍',         'weapon',  35, ['swordman', 'merchant'],                                { atk: 120 } ],
      [ 'w_104', '狂擊之劍',       'weapon',  50, ['swordman'],                                            { atk: 150, str: 3, hit: 5 } ],
      [ 'w_105', '雙手巨劍',       'weapon',  33, ['swordman'],                                            { atk: 160 } ],
      [ 'w_106', '焰形劍',         'weapon',  60, ['swordman'],                                            { atk: 200, str: 2 } ],
      [ 'w_107', '名刀 不知火',    'weapon',  75, ['swordman'],                                            { atk: 250, crit: 20, agi: 3 } ],
      [ 'w_108', '水紋劍',         'weapon',  85, ['swordman'],                                            { atk: 280, hit: 30, maxHp: 500 } ],
      [ 'w_109', '狂君之劍',       'weapon', 110, ['swordman'],                                            { atk: 350, str: 8, maxHp: 1000 } ],
      [ 'w_110', '妖刀 村正',      'weapon',  90, ['swordman'],                                            { atk: 260, crit: 30, agi: 5 } ],
      [ 'w_111', '聖劍 勝利之劍',  'weapon', 100, ['swordman'],                                            { atk: 300, str: 5, int: 5, hit: 20 } ],

      // 【斧頭 (Axes)】
      [ 'w_201', '手斧',           'weapon',  10, ['swordman', 'merchant'],                                { atk: 50 } ],
      [ 'w_202', '戰鬥斧',         'weapon',  30, ['swordman', 'merchant'],                                { atk: 130 } ],
      [ 'w_203', '雙手斧',         'weapon',  50, ['merchant', 'swordman'],                                { atk: 185 } ],
      [ 'w_204', '血斧',           'weapon',  70, ['merchant'],                                            { atk: 250, str: 5, agi: 2 } ],
      [ 'w_205', '毀滅之斧',       'weapon',  85, ['merchant'],                                            { atk: 320, vit: 3 } ],
      [ 'w_206', '颶風之斧',       'weapon', 105, ['merchant'],                                            { atk: 400, str: 10 } ],
      [ 'w_207', '斬首之斧',       'weapon',  95, ['merchant', 'swordman'],                                { atk: 350, hit: -10, str: 8 } ],

      // 【鈍器 (Maces)】
      [ 'w_301', '棍棒',           'weapon',   5, ['swordman', 'merchant', 'acolyte'],                     { atk: 23 } ],
      [ 'w_302', '流星鎚',         'weapon',  15, ['swordman', 'merchant', 'acolyte'],                     { atk: 65 } ],
      [ 'w_303', '鐵鎚',           'weapon',  25, ['swordman', 'merchant', 'acolyte'],                     { atk: 90 } ],
      [ 'w_304', '十字架',         'weapon',  40, ['acolyte'],                                             { atk: 110, matk: 80, int: 2 } ],
      [ 'w_305', '審判十字架',     'weapon',  65, ['acolyte'],                                             { atk: 140, matk: 120, int: 4 } ],
      [ 'w_306', '黃金之鎚',       'weapon',  80, ['merchant', 'acolyte'],                                 { atk: 180, hit: 20, maxHp: 300 } ],
      [ 'w_307', '復仇者之鎚',     'weapon', 100, ['acolyte', 'merchant'],                                 { atk: 260, matk: 200, str: 5, int: 5 } ],
      [ 'w_308', '尖銳的鐵鎚',     'weapon',  50, ['swordman', 'merchant'],                                { atk: 130, crit: 20 } ],

      // 【法杖 (Staffs)】
      [ 'w_401', '木杖',           'weapon',   1, ['magician', 'acolyte'],                                 { atk: 15, matk: 30 } ],
      [ 'w_402', '言靈魔杖',       'weapon',  24, ['magician', 'acolyte'],                                 { atk: 30, int: 3, matk: 90 } ],
      [ 'w_403', '生存的魔杖',     'weapon',  40, ['magician'],                                            { atk: 50, maxHp: 400, matk: 150, vit: 3 } ],
      [ 'w_404', '骷髏魔杖',       'weapon',  55, ['magician'],                                            { atk: 60, matk: 180, int: 4 } ],
      [ 'w_405', '巫術之杖',       'weapon',  70, ['magician'],                                            { atk: 60, matk: 230, dex: 4, int: 2 } ],
      [ 'w_406', '聖職之杖',       'weapon',  70, ['acolyte'],                                             { atk: 80, matk: 200, int: 5, maxSp: 150 } ],
      [ 'w_407', '毀滅魔杖',       'weapon',  90, ['magician'],                                            { atk: 100, matk: 320, int: 8 } ],
      [ 'w_408', '克羅諾斯魔杖',   'weapon', 115, ['magician'],                                            { atk: 120, matk: 450, int: 12, maxSp: 500 } ],
      [ 'w_409', '紅十字刺刃',     'weapon',  85, ['acolyte'],                                             { atk: 110, matk: 250, maxSp: 200 } ],

      // 【弓箭 (Bows)】
      [ 'w_501', '弓',             'weapon',   1, ['archer', 'thief'],                                     { atk: 15 } ],
      [ 'w_502', '十字弓',         'weapon',  18, ['archer', 'thief'],                                     { atk: 65, dex: 2 } ],
      [ 'w_503', '角弓',           'weapon',  33, ['archer'],                                              { atk: 100 } ],
      [ 'w_504', '獵弓',           'weapon',  50, ['archer'],                                              { atk: 125, hit: 10, dex: 2 } ],
      [ 'w_505', '坎弓',           'weapon',  65, ['archer'],                                              { atk: 150, dex: 3, agi: 2 } ],
      [ 'w_506', '神射手之弓',     'weapon',  80, ['archer'],                                              { atk: 180, crit: 10, dex: 5, agi: 3 } ],
      [ 'w_507', '精靈之弓',       'weapon', 100, ['archer'],                                              { atk: 250, dex: 8, hit: 30 } ],
      [ 'w_508', '巨弓',           'weapon', 120, ['archer'],                                              { atk: 350, dex: 12 } ],
      [ 'w_509', '獸人弓',         'weapon',  75, ['archer'],                                              { atk: 160, str: 2 } ],

      // 【拳刃 (Katars)】
      [ 'w_601', '拳刃',           'weapon',  40, ['thief'],                                               { atk: 105, crit: 5 } ],
      [ 'w_602', '卡塔勒拳刃',     'weapon',  55, ['thief'],                                               { atk: 148, crit: 8 } ],
      [ 'w_603', '刺客拳刃',       'weapon',  70, ['thief'],                                               { atk: 180, crit: 15, agi: 2 } ],
      [ 'w_604', '爆炎拳刃',       'weapon',  85, ['thief'],                                               { atk: 210, crit: 10, str: 3 } ],
      [ 'w_605', '斬首拳刃',       'weapon', 105, ['thief'],                                               { atk: 280, crit: 25, str: 5 } ],
      [ 'w_606', '指甲',           'weapon',  60, ['thief'],                                               { atk: 120, agi: 5, flee: 10 } ]
    ],
    
    // ================= 防具區 (Armors) =================
    armors: [
      // ---------------- 頭飾 (Helm) ----------------
      [ 'h_001', '髮圈',           'helm',     1, ['all'],                                                 { def: 1 } ],
      [ 'h_002', '頭巾',           'helm',    10, ['all'],                                                 { def: 2, maxHp: 50 } ],
      [ 'h_003', '蘋果頭飾',       'helm',    25, ['archer', 'thief'],                                     { def: 2, dex: 3 } ],
      [ 'h_004', '亡者髮箍',       'helm',    30, ['swordman', 'merchant'],                                { def: 4, agi: 2, str: 1 } ],
      [ 'h_005', '魔法師帽',       'helm',    35, ['magician'],                                            { def: 3, int: 2, maxSp: 50 } ],
      [ 'h_006', '骨製頭盔',       'helm',    50, ['swordman'],                                            { def: 7, vit: 2 } ],
      [ 'h_007', '王冠',           'helm',    70, ['all'],                                                 { def: 5, int: 3, luk: 3 } ],
      [ 'h_008', '惡魔翅膀耳飾',   'helm',    85, ['all'],                                                 { def: 2, str: 2, int: 2 } ],
      [ 'h_009', '太陽神頭盔',     'helm',   100, ['swordman', 'merchant'],                                { def: 10, str: 3, vit: 3, maxHp: 500 } ],
      [ 'h_010', '糞便帽',         'helm',    30, ['all'],                                                 { def: 2, maxHp: 100 } ],
      [ 'h_011', '貓耳髮圈',       'helm',    20, ['all'],                                                 { def: 2, agi: 2 } ],
      [ 'h_012', '兔耳髮圈',       'helm',    20, ['all'],                                                 { def: 2, luk: 2 } ],
      [ 'h_013', '鋼鐵頭盔',       'helm',    40, ['swordman', 'merchant'],                                { def: 6 } ],
      [ 'h_014', '獸人頭盔',       'helm',    55, ['swordman'],                                            { def: 8, str: 2 } ],
      [ 'h_015', '領導者頭箍',     'helm',    60, ['swordman'],                                            { def: 6, str: 1, vit: 1 } ],
      [ 'h_016', '聖職之帽',       'helm',    40, ['acolyte'],                                             { def: 4, int: 2 } ],
      [ 'h_017', '小丑帽',         'helm',    50, ['all'],                                                 { def: 3, luk: 5 } ],
      [ 'h_018', '歌舞伎面具',     'helm',    65, ['all'],                                                 { def: 4, hit: 5 } ],
      [ 'h_019', '狐狸面具',       'helm',    65, ['all'],                                                 { def: 4, agi: 3 } ],
      [ 'h_020', '舞會面具',       'helm',    65, ['all'],                                                 { def: 3, flee: 5 } ],
      [ 'h_021', '劍聖王冠',       'helm',    80, ['swordman'],                                            { def: 8, str: 3, dex: 2 } ],
      [ 'h_022', '蜂后冠',         'helm',    80, ['magician'],                                            { def: 5, int: 3, maxSp: 100 } ],
      [ 'h_023', '懶洋洋的貓',     'helm',    45, ['all'],                                                 { def: 3, flee: 10 } ],
      [ 'h_024', '天使紙袋',       'helm',    25, ['all'],                                                 { def: 1, maxHp: 50, maxSp: 50 } ],
      [ 'h_025', '惡魔侍者角',     'helm',    75, ['all'],                                                 { def: 5, str: 3, maxSp: 50 } ],
      [ 'h_026', '惡魔女僕角',     'helm',    75, ['all'],                                                 { def: 5, int: 3, maxHp: 50 } ],
      [ 'h_027', '飛行帽',         'helm',    60, ['archer'],                                              { def: 4, dex: 2, agi: 2 } ],
      [ 'h_028', '紅蝶緞帶',       'helm',    15, ['all'],                                                 { def: 2, int: 1 } ],
      [ 'h_029', '藍波利帽',       'helm',    15, ['all'],                                                 { def: 2, luk: 3 } ],
      [ 'h_030', '海盜船長帽',     'helm',    85, ['merchant', 'swordman'],                                { def: 7, str: 2, vit: 2 } ],

      // ---------------- 鎧甲 (Armor) ----------------
      [ 'a_001', '棉襯衫',         'armor',    1, ['all'],                                                 { def: 1, maxHp: 20 } ],
      [ 'a_002', '皮甲',           'armor',    5, ['all'],                                                 { def: 2, maxHp: 50 } ],
      [ 'a_003', '絲質外衣',       'armor',   10, ['magician', 'acolyte'],                                 { def: 3, maxSp: 30, int: 1 } ],
      [ 'a_004', '木製鎧甲',       'armor',   15, ['swordman', 'merchant'],                                { def: 7, maxHp: 150 } ],
      [ 'a_005', '盜賊之衣',       'armor',   20, ['thief'],                                               { def: 6, agi: 2, flee: 5 } ],
      [ 'a_006', '緊身便衣',       'armor',   20, ['archer'],                                              { def: 5, dex: 2 } ],
      [ 'a_007', '鋼鐵鎧甲',       'armor',   40, ['swordman', 'merchant'],                                { def: 12, maxHp: 400 } ],
      [ 'a_008', '聖職之衣',       'armor',   40, ['acolyte'],                                             { def: 6, int: 2, maxSp: 80 } ],
      [ 'a_009', '魔法外套',       'armor',   50, ['magician'],                                            { def: 5, int: 3, maxSp: 150 } ],
      [ 'a_010', '神射手之衣',     'armor',   65, ['archer'],                                              { def: 8, dex: 4, flee: 10 } ],
      [ 'a_011', '騎士鎧甲',       'armor',   70, ['swordman'],                                            { def: 16, maxHp: 1000, vit: 3 } ],
      [ 'a_012', '暗殺者外衣',     'armor',   75, ['thief'],                                               { def: 10, agi: 4, flee: 25 } ],
      [ 'a_013', '隕石鎧甲',       'armor',   85, ['swordman', 'merchant'],                                { def: 20, maxHp: 1500, vit: 5 } ],
      [ 'a_014', '奧丁的祝福',     'armor',   90, ['all'],                                                 { def: 10, str: 2, agi: 2, vit: 2, int: 2, dex: 2, luk: 2 } ],
      [ 'a_015', '大天使之衣',     'armor',  110, ['acolyte', 'magician'],                                 { def: 12, maxHp: 800, maxSp: 400, int: 5 } ],
      [ 'a_016', '冒險衣',         'armor',    2, ['all'],                                                 { def: 2 } ],
      [ 'a_017', '木鏈甲',         'armor',   25, ['swordman', 'merchant'],                                { def: 9, vit: 1 } ],
      [ 'a_018', '鋁合金鎧甲',     'armor',   60, ['swordman'],                                            { def: 14, vit: 2, maxHp: 600 } ],
      [ 'a_019', '鱗片鎧甲',       'armor',   55, ['swordman', 'merchant'],                                { def: 11, maxHp: 500 } ],
      [ 'a_020', '鎖子甲',         'armor',   45, ['swordman', 'merchant'],                                { def: 10 } ],
      [ 'a_021', '秘銀重甲',       'armor',   80, ['swordman'],                                            { def: 18, vit: 4, maxSp: 100 } ],
      [ 'a_022', '水屬性鎧甲',     'armor',   50, ['all'],                                                 { def: 6, maxHp: 200 } ],
      [ 'a_023', '火屬性鎧甲',     'armor',   50, ['all'],                                                 { def: 6, maxHp: 200 } ],
      [ 'a_024', '風屬性鎧甲',     'armor',   50, ['all'],                                                 { def: 6, maxHp: 200 } ],
      [ 'a_025', '地屬性鎧甲',     'armor',   50, ['all'],                                                 { def: 6, maxHp: 200 } ],
      [ 'a_026', '鮮血外衣',       'armor',   70, ['thief'],                                               { def: 8, agi: 2, str: 2, atk: 10 } ],
      [ 'a_027', '忍服 血櫻',      'armor',   65, ['thief'],                                               { def: 7, agi: 3, flee: 15 } ],
      [ 'a_028', '魔王外衣',       'armor',   95, ['magician', 'acolyte'],                                 { def: 9, int: 4, dex: 3, matk: 30 } ],
      [ 'a_029', '龍之外套',       'armor',   85, ['archer', 'thief'],                                     { def: 10, dex: 3, agi: 3 } ],
      [ 'a_030', '艾克賽利翁外套', 'armor',  100, ['all'],                                                 { def: 15, maxHp: 1000, maxSp: 200, vit: 2 } ],

      // ---------------- 披肩 (Garment) ----------------
      [ 'g_001', '連帽披肩',       'garment',  1, ['all'],                                                 { def: 1, flee: 2 } ],
      [ 'g_002', '披風',           'garment', 15, ['all'],                                                 { def: 2, flee: 5 } ],
      [ 'g_003', '斗篷',           'garment', 30, ['all'],                                                 { def: 4, flee: 10 } ],
      [ 'g_004', '生存的斗篷',     'garment', 50, ['magician', 'acolyte'],                                 { def: 3, maxHp: 200 } ],
      [ 'g_005', '金屬波利披風',   'garment', 55, ['all'],                                                 { def: 5, maxHp: 300, vit: 1 } ],
      [ 'g_006', '暗影披風',       'garment', 65, ['thief'],                                               { def: 4, flee: 25, agi: 3 } ],
      [ 'g_007', '伯爵斗篷',       'garment', 80, ['all'],                                                 { def: 6, hit: 10, flee: 15 } ],
      [ 'g_008', '巴風特之角(披風)','garment',95, ['all'],                                                 { def: 5, crit: 5, str: 2 } ],
      [ 'g_009', '墮落天使之翼',   'garment',110, ['all'],                                                 { def: 8, allStat: 3, flee: 30 } ],
      [ 'g_010', '破爛披風',       'garment', 10, ['all'],                                                 { def: 1, maxHp: 10 } ],
      [ 'g_011', '羊毛圍巾',       'garment', 55, ['all'],                                                 { def: 3, maxHp: 150 } ],
      [ 'g_012', '龍的呼吸',       'garment', 75, ['all'],                                                 { def: 6, maxHp: 250, flee: 10 } ],
      [ 'g_013', '鷹之披風',       'garment', 60, ['archer'],                                              { def: 4, dex: 2, hit: 15 } ],
      [ 'g_014', '聖天使披風',     'garment', 90, ['all'],                                                 { def: 7, maxSp: 200, int: 2 } ],
      [ 'g_015', '惡魔披風',       'garment', 90, ['all'],                                                 { def: 7, str: 2, atk: 15 } ],
      [ 'g_016', '巨大白幽靈披風', 'garment', 85, ['all'],                                                 { def: 5, flee: 20, agi: 2 } ],
      [ 'g_017', '冒險家披肩',     'garment', 20, ['all'],                                                 { def: 3 } ],
      [ 'g_018', '呢絨披風',       'garment', 40, ['all'],                                                 { def: 4, maxSp: 50 } ],
      [ 'g_019', '絲質披肩',       'garment', 40, ['magician', 'acolyte'],                                 { def: 3, int: 1 } ],
      [ 'g_020', '守護者披風',     'garment', 70, ['swordman'],                                            { def: 7, vit: 2 } ],
      [ 'g_021', '英雄披風',       'garment',105, ['swordman'],                                            { def: 9, str: 3, maxHp: 500 } ],
      [ 'g_022', '魔王披風',       'garment',105, ['magician', 'acolyte'],                                 { def: 6, int: 3, maxSp: 300 } ],
      [ 'g_023', '艾克賽利翁披風', 'garment',100, ['all'],                                                 { def: 10, flee: 20 } ],
      [ 'g_024', '勇者披肩',       'garment', 90, ['all'],                                                 { def: 8, maxHp: 300 } ],
      [ 'g_025', '亡靈披風',       'garment', 80, ['all'],                                                 { def: 5, luk: 4 } ],
      [ 'g_026', '神聖披風',       'garment', 85, ['acolyte'],                                             { def: 6, maxSp: 150, int: 2 } ],
      [ 'g_027', '幻影披風',       'garment', 95, ['thief'],                                               { def: 6, flee: 25 } ],
      [ 'g_028', '飛龍披風',       'garment', 85, ['archer'],                                              { def: 7, dex: 3 } ],
      [ 'g_029', '戰鬥披風',       'garment', 65, ['swordman', 'merchant'],                                { def: 6, str: 1 } ],
      [ 'g_030', '秘銀披風',       'garment', 75, ['all'],                                                 { def: 8 } ],

      // ---------------- 鞋靴 (Shoes) ----------------
      [ 's_001', '涼鞋',           'shoes',    1, ['all'],                                                 { def: 1, maxHp: 15 } ],
      [ 's_002', '皮靴',           'shoes',   15, ['all'],                                                 { def: 2, maxHp: 50 } ],
      [ 's_003', '長靴',           'shoes',   30, ['all'],                                                 { def: 4, maxHp: 150 } ],
      [ 's_004', '魔法師之靴',     'shoes',   45, ['magician'],                                            { def: 2, maxSp: 100, int: 2 } ],
      [ 's_005', '戰士長靴',       'shoes',   50, ['swordman', 'merchant'],                                { def: 6, maxHp: 400, str: 1 } ],
      [ 's_006', '敏捷長靴',       'shoes',   65, ['thief', 'archer'],                                     { def: 5, agi: 4, flee: 20 } ],
      [ 's_007', '玻璃鞋',         'shoes',   75, ['all'],                                                 { def: 3, luk: 5, matk: 30 } ],
      [ 's_008', '時光力量戰靴',   'shoes',  100, ['swordman', 'merchant', 'thief'],                       { def: 8, str: 5, maxHp: 800, atk: 50 } ],
      [ 's_009', '時光靈巧戰靴',   'shoes',  100, ['archer'],                                              { def: 8, dex: 5, maxHp: 500, maxSp: 100, atk: 30 } ],
      [ 's_010', '輕便鞋',         'shoes',   10, ['all'],                                                 { def: 2, flee: 2 } ],
      [ 's_011', '戰鬥靴',         'shoes',   35, ['swordman', 'merchant'],                                { def: 5, maxHp: 200 } ],
      [ 's_012', '鋼鐵長靴',       'shoes',   60, ['swordman'],                                            { def: 8, vit: 2 } ],
      [ 's_013', '秘銀長靴',       'shoes',   80, ['swordman', 'merchant'],                                { def: 10, vit: 3, maxHp: 400 } ],
      [ 's_014', '兔斯基鞋',       'shoes',   40, ['all'],                                                 { def: 3, agi: 2 } ],
      [ 's_015', '兔子拖鞋',       'shoes',   25, ['all'],                                                 { def: 2, luk: 3 } ],
      [ 's_016', '聖職之靴',       'shoes',   55, ['acolyte'],                                             { def: 4, int: 2, maxSp: 100 } ],
      [ 's_017', '魔王長靴',       'shoes',   95, ['magician', 'acolyte'],                                 { def: 5, int: 4, maxSp: 250 } ],
      [ 's_018', '變異的靴子',     'shoes',   85, ['all'],                                                 { def: 7, maxHp: 1000, maxSp: 300 } ],
      [ 's_019', '審判之靴',       'shoes',   90, ['acolyte'],                                             { def: 6, int: 3, matk: 50 } ],
      [ 's_020', '龍之長靴',       'shoes',   85, ['archer', 'thief'],                                     { def: 6, agi: 3, maxHp: 300 } ],
      [ 's_021', '冒險家長靴',     'shoes',   20, ['all'],                                                 { def: 3, maxHp: 100 } ],
      [ 's_022', '羊毛長靴',       'shoes',   65, ['all'],                                                 { def: 5, maxHp: 250 } ],
      [ 's_023', '艾克賽利翁長靴', 'shoes',  100, ['all'],                                                 { def: 10, maxHp: 500, maxSp: 200 } ],
      [ 's_024', '幻影長靴',       'shoes',   90, ['thief'],                                               { def: 5, flee: 15, agi: 4 } ],
      [ 's_025', '英雄長靴',       'shoes',  105, ['swordman'],                                            { def: 12, vit: 4, maxHp: 800 } ],
      [ 's_026', '銀色長靴',       'shoes',   45, ['all'],                                                 { def: 5, maxSp: 50 } ],
      [ 's_027', '時光智力戰靴',   'shoes',  100, ['magician', 'acolyte'],                                 { def: 6, int: 5, maxSp: 300, matk: 50 } ],
      [ 's_028', '時光體力戰靴',   'shoes',  100, ['swordman'],                                            { def: 10, vit: 5, maxHp: 1200 } ],
      [ 's_029', '時光敏捷戰靴',   'shoes',  100, ['thief'],                                               { def: 6, agi: 5, flee: 30, atk: 20 } ],
      [ 's_030', '時光幸運戰靴',   'shoes',  100, ['all'],                                                 { def: 6, luk: 5, crit: 15 } ],

      // ---------------- 盾牌 (Shields) ----------------
      [ 'sh_001', '圓盾',          'shield',  10, ['all'],                                                 { def: 3 } ],
      [ 'sh_002', '鐵盾',          'shield',  30, ['swordman', 'merchant'],                                { def: 6 } ],
      [ 'sh_003', '魔法書',        'shield',  35, ['magician'],                                            { def: 2, int: 2, matk: 30 } ],
      [ 'sh_004', '鋼盾',          'shield',  50, ['swordman', 'merchant'],                                { def: 9, vit: 1 } ],
      [ 'sh_005', '聖職之盾',      'shield',  55, ['acolyte'],                                             { def: 5, maxSp: 80, int: 1 } ],
      [ 'sh_006', '謊言紀錄本',    'shield',  70, ['magician'],                                            { def: 4, int: 3, matk: 50 } ],
      [ 'sh_007', '十字盾',        'shield',  85, ['swordman'],                                            { def: 12, vit: 3, maxHp: 500 } ],
      [ 'sh_008', '巴基力的鋼盾',  'shield', 105, ['all'],                                                 { def: 15, allStat: 2, maxHp: 800, maxSp: 200 } ],
      [ 'sh_009', '護盾',          'shield',   5, ['all'],                                                 { def: 2 } ],
      [ 'sh_010', '巨盾',          'shield',  45, ['swordman'],                                            { def: 10, flee: -10 } ],
      [ 'sh_011', '鏡盾',          'shield',  65, ['swordman', 'merchant'],                                { def: 8, maxHp: 300 } ],
      [ 'sh_012', '聖文盾牌',      'shield',  75, ['acolyte'],                                             { def: 7, int: 2, maxSp: 150 } ],
      [ 'sh_013', '記憶之書',      'shield',  80, ['magician'],                                            { def: 5, int: 4, matk: 80 } ],
      [ 'sh_014', '盤石盾',        'shield',  80, ['swordman', 'merchant'],                                { def: 11, vit: 2 } ],
      [ 'sh_015', '刺尾龍盾',      'shield',  90, ['all'],                                                 { def: 9, maxHp: 400 } ],
      [ 'sh_016', '薔薇鋼盾',      'shield',  95, ['swordman'],                                            { def: 13, maxHp: 600 } ],
      [ 'sh_017', '鈽鐳金盾',      'shield', 100, ['swordman', 'merchant'],                                { def: 14, vit: 3 } ],
      [ 'sh_018', '魔力石盾',      'shield',  90, ['magician'],                                            { def: 6, maxSp: 300 } ],
      [ 'sh_019', '魔法反射盾',    'shield',  95, ['swordman'],                                            { def: 10, maxHp: 500 } ],
      [ 'sh_020', '冒險家之盾',    'shield',  20, ['all'],                                                 { def: 4 } ],
      [ 'sh_021', '獸人族盾牌',    'shield',  60, ['all'],                                                 { def: 7, maxHp: 200 } ],
      [ 'sh_022', '皇家盾牌',      'shield',  85, ['swordman'],                                            { def: 12, maxHp: 400 } ],
      [ 'sh_023', '龍之盾',        'shield',  75, ['swordman', 'merchant'],                                { def: 9, maxHp: 300 } ],
      [ 'sh_024', '魔王之盾',      'shield', 105, ['magician', 'acolyte'],                                 { def: 8, maxSp: 200, int: 3 } ],
      [ 'sh_025', '幻影圓盾',      'shield',  90, ['thief'],                                               { def: 7, flee: 10 } ],
      [ 'sh_026', '艾克賽利翁盾',  'shield', 100, ['all'],                                                 { def: 12, maxHp: 500, maxSp: 100 } ],
      [ 'sh_027', '守護者之盾',    'shield',  80, ['swordman'],                                            { def: 11, vit: 2 } ],
      [ 'sh_028', '英雄之盾',      'shield', 110, ['swordman'],                                            { def: 16, vit: 5, maxHp: 1000 } ],
      [ 'sh_029', '黃金之盾',      'shield',  85, ['all'],                                                 { def: 9, luk: 3 } ],
      [ 'sh_030', '聖騎士之盾',    'shield',  95, ['swordman'],                                            { def: 14, vit: 4, int: 2 } ]
    ],

    // ================= 飾品區 (Accessories) =================
    accessories: [
      [ 'ac_001', '夾子',          'acc',     10, ['all'],                                                 { maxSp: 30 } ],
      [ 'ac_002', '力量戒指',      'acc',     20, ['swordman', 'merchant', 'thief'],                       { atk: 15, str: 2 } ],
      [ 'ac_003', '智力耳環',      'acc',     20, ['magician', 'acolyte'],                                 { int: 2, maxSp: 50, matk: 20 } ],
      [ 'ac_004', '敏捷胸針',      'acc',     20, ['archer', 'thief'],                                     { flee: 5, agi: 2 } ],
      [ 'ac_005', '幸運珠鍊',      'acc',     20, ['all'],                                                 { crit: 3, luk: 2 } ],
      [ 'ac_006', '體力項鍊',      'acc',     20, ['swordman', 'merchant'],                                { maxHp: 150, vit: 2 } ],
      [ 'ac_007', '靈巧手套',      'acc',     20, ['archer'],                                              { hit: 10, dex: 2 } ],
      [ 'ac_008', '防禦手套',      'acc',     50, ['all'],                                                 { def: 2, maxHp: 150 } ],
      [ 'ac_009', '盜賊戒指',      'acc',     70, ['thief'],                                               { str: 1, agi: 1, crit: 5 } ],
      [ 'ac_010', '防禦戒指',      'acc',     60, ['all'],                                                 { def: 3, vit: 1 } ],
      [ 'ac_011', '戰神戒指',      'acc',     80, ['swordman'],                                            { str: 3, maxHp: 300, atk: 20 } ],
      [ 'ac_012', '專家戒指',      'acc',     80, ['all'],                                                 { maxSp: 100, matk: 30 } ],
      [ 'ac_013', '詛咒紅寶石',    'acc',     40, ['all'],                                                 { luk: -5, atk: 30, matk: 30 } ],
      [ 'ac_014', '髮夾',          'acc',      1, ['all'],                                                 { maxSp: 10 } ],
      [ 'ac_015', '體力別針',      'acc',     45, ['swordman', 'merchant'],                                { maxHp: 200, vit: 3 } ],
      [ 'ac_016', '靈巧別針',      'acc',     45, ['archer'],                                              { hit: 15, dex: 3 } ],
      [ 'ac_017', '幸運別針',      'acc',     45, ['all'],                                                 { crit: 5, luk: 3 } ],
      [ 'ac_018', '敏捷別針',      'acc',     45, ['thief', 'archer'],                                     { flee: 8, agi: 3 } ],
      [ 'ac_019', '智力別針',      'acc',     45, ['magician', 'acolyte'],                                 { maxSp: 80, int: 3 } ],
      [ 'ac_020', '力量別針',      'acc',     45, ['swordman', 'merchant'],                                { atk: 25, str: 3 } ],
      [ 'ac_021', '奧爾里昂的手套','acc',     90, ['magician'],                                            { dex: 2, matk: 50 } ],
      [ 'ac_022', '奧爾里昂的項鍊','acc',     90, ['magician'],                                            { int: 2, maxSp: 150 } ],
      [ 'ac_023', '核心01',        'acc',     85, ['all'],                                                 { def: 1, int: 2, maxSp: 100 } ],
      [ 'ac_024', '核心02',        'acc',     85, ['all'],                                                 { def: 1, str: 2, atk: 20 } ],
      [ 'ac_025', '核心03',        'acc',     85, ['all'],                                                 { def: 1, agi: 2, flee: 10 } ],
      [ 'ac_026', '核心04',        'acc',     85, ['all'],                                                 { def: 1, dex: 2, hit: 10 } ],
      [ 'ac_027', '魔力手鐲',      'acc',     65, ['magician', 'acolyte'],                                 { int: 1, maxSp: 50, matk: 15 } ],
      [ 'ac_028', '詛咒胸針',      'acc',     75, ['thief'],                                               { crit: 10, luk: -2 } ],
      [ 'ac_029', '刺客手銬',      'acc',     85, ['thief'],                                               { agi: 2, str: 2, crit: 5 } ],
      [ 'ac_030', '弓箭手面甲',    'acc',     70, ['archer'],                                              { dex: 3, hit: 20 } ]
    ]
  }
};